### ISSUE TITLE
sql语句中不支持 select

### ISSUE THREAD

**Issue by zzbsss** [zhp8341/flink-streaming-platform-web#10]
sql语句中不支持 select
语句中有select会报错

**Comment by JingZhang-Cherish** [comment]
你把你的详细配置贴出来看看呢

**Comment by zhp8341** [comment]
不支持直接select 只能是insert into select

**Comment by JasonLeeCoding** [comment]
你可以建一个 print 的表 然后 insert into select ... 如果想要直接 select 的话代码里面需要转成 stream 然后在 print
