### ISSUE TITLE
本地开启yarn-session模式的情况下，提交作业正常运行，但是web界面会显示失败

### ISSUE THREAD

**Issue by JingZhang-Cherish** [zhp8341/flink-streaming-platform-web#11]
本地随意开启一个yarn-session
./bin/yarn-session.sh -d
resourcemanger页面可以看见jobmanger已经开启
此时提交作业通过standalone模式提交，作业被提交到yarn-session的jobmanager中，但是web界面显示提交作业失败。

**Comment by zhp8341** [comment]
暂时还不支持yarn-session模式
