### ISSUE TITLE
appId无法获取

### ISSUE THREAD

**Issue by chenxiaoliang0901** [zhp8341/flink-streaming-platform-web#15]
日志报错appId无法获取，请问是什么原因导致的，配置如下：
![image](https://user-images.githubusercontent.com/32791398/106249864-d924bf00-624d-11eb-95f9-a1fd29a73c87.png)

**Comment by tomasyl** [comment]
我也遇到了，然后把命令直接贴到linux里去执行，可以看到具体错误是sql问题，甚至给出了正确的connect参数写法，但日志里只有appid 无法获取

**Comment by zhp8341** [comment]
appid获取失败 请查看flink客户端日志、web日志,如果都没有发现错误,请去集群查看任务的历史日志
