### ISSUE TITLE
sql文件挺多问题的

### ISSUE THREAD

**Issue by bulolo** [zhp8341/flink-streaming-platform-web#78]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/10026498/156681336-a899e853-8588-48bb-8ed0-cac7a0fa874c.png">

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/10026498/156681355-578dbed9-feb4-4968-af80-dbfabce1f385.png">

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/10026498/156681436-65e95fe3-4d7b-49b8-9158-18f3e240e537.png">

使用docker体验，所以密码到底是多少？
https://github.com/zhp8341/flink-streaming-platform-web/blob/master/docs/docker-demo.md

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/10026498/156681619-63eb865a-b0fb-4c86-992c-5f819f3ccad7.png">
这个sql文件挺多问题的，用户都没插入成功,提了个pull requests

**Comment by zhp8341** [comment]
docker版本镜像已经更新优化  https://github.com/zhp8341/flink-streaming-platform-web/blob/master/docs/docker-demo.md
