### ISSUE TITLE
想更换到flink 1.11.1 版本 ，然而打包总是报错org.apache.flink.table.planner.parse.CalciteParser;  找不到

### ISSUE THREAD

**Issue by weijunh** [zhp8341/flink-streaming-platform-web#83]
想更换到flink 1.11.1 版本 ，然而打包总是报错org.apache.flink.table.planner.parse.CalciteParser;  找不到

**Comment by zhp8341** [comment]
删除org.apache.flink.table.planner.parse.CalciteParse 重新导入下
