### ISSUE TITLE
Docker部署的Flink客户端日志的ip是docker内部ip，WebUI访问不到

### ISSUE THREAD

**Issue by lglfa** [zhp8341/flink-streaming-platform-web#85]
![image](https://user-images.githubusercontent.com/18619269/167600044-1849d808-41b5-4b83-9458-791bbd1189b2.png)

**Comment by zhp8341** [comment]
端口映射下  ip改成docker的宿主机IP就可以访问了

**Comment by lglfa** [comment]
docker好改，现在大都使用容器云平台，这种平台的容器ip都是创建的时候分配的
