### ISSUE TITLE
项目启动后，一直报错selectLastIp is null

### ISSUE THREAD

**Issue by Weipleasure** [zhp8341/flink-streaming-platform-web#92]
![3~5_V6EH025Q{K@F_F 3@0O](https://user-images.githubusercontent.com/20699916/182566190-4f1e8411-89e4-45bd-8d61-bead9a7e11ac.png)

**Comment by yeyhuan** [comment]
建议你去查一下时区的问题，jdbc连接那里默认加了serverTimezone=UTC，会导致如下图所示的sql查询不到数据

![image](https://user-images.githubusercontent.com/56808442/184116633-9a44c26b-5b8a-4fa4-839f-7ebc573669aa.png)

解决方法：serverTimezone=GMT%2B8

**Comment by zhp8341** [comment]
参考楼上的解决方式
